Fix RSpec and Rake conflict
At 2.3.3 version specs are already failing.

```
$ bundle exec rake
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007fcc8bbf3858>
/Users/abinoam/.rvm/gems/ruby-2.3.3/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:143:in `initialize'
/Users/abinoam/diffy/Rakefile:6:in `new'
/Users/abinoam/diffy/Rakefile:6:in `<top (required)>'
/Users/abinoam/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/abinoam/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/abinoam/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Travis has already issued a warning.

See: https://travis-ci.org/samg/diffy/jobs/171993776

```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```

Just unlocking RSpec version solves the resolution problem.
All specs keep passing green.